### ISSUE TITLE
Bug in Exercise 02.01

### ISSUE THREAD

**Issue by amazingvoice** [PacktPublishing/Clean-Android-Architecture#3]
place: The apply() method of DispatcherTestRule
cause: calling base?.evaluate() will make the corresponding test method to run twice with the Dispatchers.resetMain() called before the 2nd run of the test method, which fails the test.

**Comment by alexandrudumbravan** [comment]
Hello,

I've looked over the issue and I'm not sure if you're running the exercise as is or implementing something different based on it. I'll try to go over everything in that rule to justify it's role and how it might go wrong.
Calling base?.evaluate() is required for test rules because this is what runs the actual test. https://www.baeldung.com/junit-4-rules.

When things go wrong are when tests are run in parallel. So let's say NumberAdderTest has multiple tests and you opt to run them in parallel then what will happen is that the first test changes Dispatchers with  Dispatchers.setMain(testDispatcher) then runs the test then finishes and calls Dispatchers.resetMain(). If another test starts after Dispatchers.resetMain() then you will have the issue you mentioned. If you want to opt for parallel tests then all global configurations should be avoided and instead find a way to inject TestCoroutineDispatcher into the targets you want to test.

I hope that clarifies the issue.

Thank you.

**Comment by bsingha27** [comment]
Hi @amazingvoice,
I hope Alexandru's response has clarified your issue. We are closing this issue for now. If you encounter any further issues with the code, please feel free to open a new one.
Thanks.
